package com.fanzzi.backend.channel.dto.request;

import com.fanzzi.backend.channel.enums.ChannelType;
import com.fanzzi.backend.channel.enums.ChannelVisibility;
import jakarta.validation.constraints.*;
import lombok.Data;

/**
 * =====================================================
 * 📥 CREATE CHANNEL REQUEST (MVP)
 * =====================================================
 * Contains only the minimal data required to create a channel.
 *
 * Advanced settings (privacy, monetization tiers, moderation,
 * analytics, etc.) are configured later by the channel owner.
 */
@Data
public class CreateChannelRequest {

    // =====================================================
    // 📝 CHANNEL NAME
    // =====================================================

    /**
     * Display name of the channel.
     * Must be unique enough for slug generation.
     */
    @NotBlank(message = "Channel name is required")
    @Size(min = 3, max = 80,
            message = "Name must be 3–80 characters")
    private String name;

    // =====================================================
    // 📄 DESCRIPTION
    // =====================================================

    /**
     * Optional channel description/about text.
     */
    @Size(max = 500,
            message = "Description too long")
    private String description;

    // =====================================================
    // 🖼 PROFILE IMAGE (STORAGE KEY)
    // =====================================================

    /**
     * Storage key of uploaded profile image (e.g., R2/S3 key).
     * Full URL is generated by backend/CDN.
     */
    private String profileImageKey;

    // =====================================================
    // 🔐 VISIBILITY
    // =====================================================

    /**
     * PUBLIC → Accessible via slug
     * PRIVATE → Accessible via invite token
     */
    @NotNull(message = "Visibility required")
    private ChannelVisibility visibility;

    // =====================================================
    // 💰 CHANNEL TYPE
    // =====================================================

    /**
     * FREE → No subscription required
     * PAID → Requires monthly subscription
     */
    @NotNull(message = "Channel type required")
    private ChannelType type;

    // =====================================================
    // 💸 MONTHLY PRICE (PAID CHANNELS ONLY)
    // =====================================================

    /**
     * Required only when type = PAID.
     * Must be positive.
     */
    @Positive(message = "Price must be positive")
    private Long monthlyPrice;

    // =====================================================
    // 🌍 DISCOVERY & CLASSIFICATION
    // =====================================================

    /**
     * Channel category for filtering (Tech, Gaming, etc.)
     * Optional but recommended for explore features.
     */
    private String category;

    /**
     * Primary content language (en, hi, etc.)
     */
    private String language;

    // =====================================================
    // 🔍 DISCOVERABILITY
    // =====================================================

    /**
     * Whether channel appears in public explore/search.
     * Defaults to TRUE in backend if null.
     */
    private Boolean discoverable;
}